---
title: "Time-to-Event Estimation with Unreliably Reported Events in Medicare Health Plan Payment"

date: last-modified

author:
  - name: Oana M. Enache
    email: oenache@stanford.edu
    affiliations: 
        - id: 1
          name: Stanford University School of Medicine
          department: Department of Biomedical Data Science
          address: Edwards Building, 300 Pasteur Drive
          city: Stanford, CA
          postal-code: 94304
    attributes:
        corresponding: true
  - name: Sherri Rose
    affiliations: 
        - id: 2
          name: Stanford University
          department: Department of Health Policy
          address: Encina Commons, 615 Crothers Way
          city: Stanford, CA
          postal-code: 94305
    attributes:
        corresponding: false

abstract: |
    **Objective**: To propose time-to-event estimators that help evaluate incident diagnostic coding and possible upcoding in Medicare as well as introduce an open-source software package that enables more reproducible methods development relevant to Medicare billing behavior. \
    **Study setting and Design**: Observational analysis of simulated upcoding based on coding by insurers or providers that may be incentivized by Medicare Advantage risk adjustment. \
    **Data Sources and Analytic Sample**: Two years of separately simulated incident health condition coding data for a Medicare Advantage population and a Traditional Medicare population where coding patterns are aligned with known practices in each program. \
    **Principal Findings**: We propose several novel time-to-event estimators of incident coding intensity and possible upcoding in Medicare Advantage, including accounting for unreliable reporting. We demonstrate estimator performance in simulated data leveraging the National Institutes of Health's All of Us study and also develop an open source R package to simulate longitudinal realistic labeled upcoding data, which were not previously available for researchers. In simulations, our novel estimators recovered differences in upcoding within and across monitoring periods. Undercoding had a limited effect on our novel estimators while an existing estimator was more sensitive to undercoding. \
    **Conclusions**: Our proposed estimators can help researchers and policymakers track new coding behaviors (e.g., as may be incentivized by risk adjustment formula updates) earlier and at scale while accounting for several real-world data considerations. Further, the R package we provide can be used to improve the development, accessibility, and reproducible evaluation of coding intensity and upcoding methodology. 

keywords: 
 - survival analysis
 - restricted mean time lost 
 - restricted mean survival time 
 - Medicare Advantage
 - upcoding
 - risk adjustment

bibliography: bibliography.bib  
csl: american-medical-association.csl

geometry:
  - inner=1in
  - outer=1in
  - top=1in
  - bottom=1in
  
mainfont: "Times New Roman"
fontsize: 12pt
whitespace: none
linestretch: 1

format: 
 elsevier-pdf:
  keep-tex: true
  fig-pos: H
  number-sections: true
  appendix: true
  cite-method: citeproc
---

{{< pagebreak >}}

[**Callout Box**]{.underline}

**What is known on this topic:**

-   The present structure of health plan payment in Medicare Advantage incentivizes high coding intensity and possible upcoding, costing the federal government billions annually without clear benefit to beneficiaries.

-   No individual-level labeled upcoding data are currently available to researchers, making developing and evaluating coding intensity and upcoding measures and estimators challenging.

-   Current coding intensity estimation approaches largely count diagnoses within a fixed time period (e.g., a year) and do not account for issues like Traditional Medicare undercoding.

**What this study found:**

-   This study introduces a set of time-to-event estimators of coding intensity that address some unrealistic assumptions of widely-used existing estimators.

-   Providing an open-source R package enables the simulation of realistic baseline, undercoded, and upcoded data over time, including labels for upcoding instances.

-   The proposed estimators and software package can help researchers better evaluate Medicare providers and insurers' coding behaviors and identify health plan payment improvements at scale.

# Introduction

Medicare is a federally funded insurance program administered by the Centers for Medicare and Medicaid Services (CMS), supporting over 69 million Americans who are aged 65 years and older or chronically disabled [@Ochieng2025-bv]. Beneficiaries choose between receiving coverage through Traditional Medicare (TM) or Medicare Advantage (MA). TM beneficiaries' care is generally paid directly by CMS for each service provided. In contrast, MA beneficiaries receive health insurance from private insurers who are paid by CMS for each beneficiary's anticipated health needs.

These prospective health plan payments are determined by risk adjustment, currently an ordinary least squares linear regression with binary demographic and health diagnostic variables, each of which has a positive coefficient. The outcome of this algorithm is a risk score, which is used to adjust a benchmark payment amount per beneficiary [@Pope2004-tv; @Ellis2018-mr]. There are 115 variables (hierarchical condition categories or HCCs) that report the purported presence or absence of certain health conditions in the formula [@Centers_for_Medicare_and_Medicaid_Services2023-zf], which is also referred to as CMS-HCC [@Ellis2018-mr]. Although HCCs overall correspond to dozens of distinct health conditions, certain subsets of these variables also represent severity levels within the same condition and are therefore billed in a mutually exclusive manner, where payment increases with severity. For example, in the current version (version 28 or V28) of CMS-HCC an insurer can only be paid for coding one of HCC125-127, which correspond to severe, moderate, and mild or unspecified dementia respectively [@Ellis2018-mr; @Centers_for_Medicare_and_Medicaid_Services2023-zf].

Importantly, insurers retain the amount of money paid by CMS regardless of what care their beneficiaries actually receive [@Pope2004-tv; @Ellis2018-mr]. This and the structure of CMS-HCC incentivizes insurers to code for as many diagnoses as possible to increase profits [@geruso2020; @joiner2024; @Medpac2025-uh]. Insurers coding for more diagnoses or more severe diagnoses than is accurate is referred to as upcoding. This is thought to cost CMS tens of billions of dollars annually in unnecessary spending to private insurers without clear benefit to MA beneficiaries [@Medpac2025-uh]. Most major MA insurers have also been accused of fraud due to billing practices at least once in recent years by the United States Department of Justice, largely using information from whistleblowers or other manual audits [@Abelson2023-gr; @Centers_for_Medicare_Medicaid_Services2023-dy; @Constantino2025-qf; @DOJ2026-vd].

Prior literature has also estimated upcoding inconsistently for several decades [@joiner2024], in part because there are a number of barriers for researchers working on such methods. First, it is difficult to definitively identify upcoding when researchers only have access to national Medicare claims data, as is typical. Second, gaining access to individual-level Medicare data is a time-consuming and sometimes inaccessible process. Third, there are limited national data resources describing co-occurring health conditions free of coding incentives in older adults [@rose2016; @chernew2021; @McWilliams2025-hz]. Fourth, labeled upcoding data to evaluate estimators are not available. This also means that comparing proposed methods is challenging, as the data used to develop or evaluate methods are often not able to be shared.

Thus, assessment of upcoding in MA is usually done by comparing prevalence of coding of beneficiaries, or coding intensity, to coding intensity of similar health conditions in TM, with slight variation on inclusion and exclusion criteria used [@McGuire2025-bp]. However, TM is known to have underreporting (i.e., undercoding) of health conditions [@Ellis2018-mr; @Ghoshal-Datta2024-io]. This type of unreliable reporting is important to account for as measures of differences between the programs will likely be inflated otherwise. Alternative reference data besides TM diagnoses have been explored in prior work [@jacobs2018; @kronick2021a] but remain underutilized.

To our knowledge, time-to-event (TTE) analyses (i.e., survival analysis) have not previously been used to evaluate coding behaviors in Medicare. TTE analyses typically aim to compare differences between groups drawn from two or more populations in a randomized clinical trial or observational study with censoring, one type of incompletely observed data. This may include plotting events over time using either Kaplan-Meier or cumulative incidence curves [@James2021-ej; @Geskus2020-tb].

Most commonly, hazard ratios are used to estimate the magnitude of the effect between groups [@Hernan2010-qs; @Chappell2016-gr; @Uno2020-hk]. For example, a review of 66 clinical trials with TTE primary outcomes across four major medical journals found that 80% of trials reported a hazard ratio as a main finding, while only 21% of studies reported any alternative approaches [@Jachno2019-bk]. However, hazard ratios are unintuitive to interpret [@Tian2014-xr; @Chappell2016-gr] and rely on an often unrealistic proportional hazards assumption [@Hernan2010-qs; @Trinquart2016-cv; @Jachno2019-bk]. Researchers sometimes also compare mean or median survival, but this omits most of the data and may not be estimable in certain scenarios [@Chappell2016-gr; @Tian2020-sw].

Furthermore, alternate approaches are needed if competing risks, or when there is more than one mutually exclusive outcome, are present. Despite being pervasive in health studies, competing risks are frequently ignored, which can result in biased estimates of the primary outcome [@Austin2017-nm; @Geskus2020-tb; @Conner2021-ac]. Additional important considerations in TTE analyses include the choice of monitoring period (i.e., the time window analyzed between a pre-specified origin and end time) and comparison group.

Although first proposed in 1949 [@Irwin1949-ez], restricted mean survival time (RMST) was revisited for TTE estimation in more contemporary literature [@Royston2011-sz; @Tian2014-xr; @Uno2014-ul; @Trinquart2016-cv; @Zhao2016-ca] because it addresses many of the issues of more popular approaches. RMST is defined as the area under the survival curve of time to an event for a single monitoring period. It can be interpreted as the mean time to event for all study participants followed in that monitoring period [@Tian2014-xr]. With large enough sample sizes, it is estimable nonparametrically, does not require proportional hazards, and is censoring independent [@Tian2014-xr].

In TTE analyses with a single outcome, the area above the survival curve in one monitoring period (or, the end time minus the RMST) is the restricted mean time lost (RMTL) [@Andersen2013-jm]. RMTL has a number of appealing features, including that it can straightforwardly be extended to correspond to the area below cause- or event-specific cumulative incidence curves in competing risk settings [@Andersen2013-jm; @Calkins2018-ed; @Conner2021-ac]. In such scenarios, an event-specific RMTL corresponds to the area below its cumulative incidence curve and can be interpreted as the mean time without that particular event in a monitoring period [@Conner2021-ac], or a summary of both how many and when events occur in that time. Differences in RMTL between two groups (for example, a treatment and control or other comparison group) can also be used to quantify effects [@Wu2022-mx].

We expand RMTL estimation approaches for use in evaluating incident HCC coding in MA following CMS-HCC formula updates. Here, individual HCCs and sets of mutually exclusive HCCs corresponding to severity levels of a single health condition are our events of interest. We propose that the latter HCC type can be considered conceptually analogous to competing risks in TTE analyses because only one HCC can be recorded and paid for at a time. An event occurs when an a diagnosis not reported in prior monitoring periods is reported by an insurer.

Besides being a unique application of TTE methods in itself, our approach expands on prior RMTL-based methodological work by also accounting for potential underreporting of events in TM. Further, we propose a novel estimation approach for identifying one type of possible severity-based upcoding, by which we mean beneficiaries who have a lower-severity version of an HCC being coded with the most severe HCC of that health condition. Other estimators also apply to a different form of upcoding that we call any-available, where any beneficiaries previously not coded with a given HCC could be reported as having that health condition, potentially fraudulently. When upcoding has not been concretely confirmed (as is most often the case in real-world settings) we reflect this by describing it as possible upcoding.

Our contributions also include the creation of an R package to simulate co-occurring HCCs based on older American adults' self-reported health conditions from a large national survey. Self-reported data are not impacted by coding incentives to the same degree as claims or electronic health record data [@rose2016; @chernew2021; @McWilliams2025-hz] and enable analysis of incident coding without underreporting. Our package additionally allows users to modify these baseline data by either underreporting existing baseline diagnoses (realistic to TM data) or upcoding specific HCCs over time, which are then labeled. Labeled upcoding data did not previously exist---existing individual-level Medicare do not contain this information---so these simulated data are broadly useful for methods development in health policy.

# Methods

## Estimation approach

In our setting, TTE and time to reported event are equivalent because we do not observe each coding event directly; because our estimates are over entire monitoring periods, we do not consider potential delays in reporting events to have notable impact. Multiple events may be reported at each of several time points within one or more monitoring periods (e.g., a monitoring period could be a calendar year where each time interval is three months). If there are multiple monitoring periods (e.g., years) where events are reported, then each monitoring period has a separate origin and end time between which events are reported. Our goals are to both (1) evaluate reporting of incident events within one monitoring period and (2) compare incident event reporting across sequential monitoring periods.

### Notation for incident events

An event (reported coding of either a single HCC or a single member of a set of HCCs corresponding to severity levels of one health condition) is considered incident if it was not reported in prior monitoring periods. The reporting of an incident event is represented by a vector $S$, with $s \ge 1$ possible mutually exclusive subtype events. $S$ encodes which of these events occurs first, analogous to competing risks. These are referred to as competing events and examined in a event-specific manner. When $s > 1$, the possible values $S$ can take are written $s \in \{1, ..., k\}$ in order of increasing severity. Incident reporting of these events is observed in a set of two independent groups labeled by $g$, where $g=0$ is a comparison group for $g=1$, over $m \ge 2$ pre-specified monitoring periods.

For a given monitoring period, group, and subtype event, $T$ is the true time to incident reporting for that event only. In addition, $C$ is the time to censoring not due to any competing event. We observe $Y= \text{min}(T, C)$ and know whether censoring or reporting of the event happened first, which is denoted by $\Delta = I(T \le C)$. Our observed data are therefore of the form $\{(Y_1, S_1\Delta_1),...,(Y_n, S_n\Delta_n)\}$ for the $n$ total events reported within the monitoring period. Ordered discrete event reporting times are $t_1 < t_2 < ... < \tau$, where $\tau$ is the end time of the monitoring period. A single time of event reporting in a monitoring period is denoted $t_i$. Finally, when comparing across groups or monitoring periods we add a respective $g$ or $m$ subscript to the notation above. Sequential monitoring periods are written as $m-1$ and $m$.

### Notation for reference events

We use a set of reference events, or HCCs distinct from the HCCs examined for incident reporting, to estimate underreporting as others have done previously [@Ellis2018-mr; @Ghoshal-Datta2024-io]. In theory, reference HCCs reported in one monitoring period should continue to be reported at equal rates in subsequent monitoring periods. However, in practice some reference events (and events in $g=0$ more broadly) may be underreported. Reference events are denoted as a vector $S^*$ of $h$ distinct HCCs, which can take values $s^* \in \{1, ..., h\}$. None of these reference events have competing events. The persistence of a given reference event $s^*$ in monitoring period $m$, meaning the proportion of individuals coded with $s^*$ in monitoring period $m$ who were previously coded with $s^*$ in monitoring period $m-1$, is $q_{s^*,m}$ in line with prior work [@McGuire2025-bp].

### Target estimands

Before describing our estimands for incident event reporting (in paragraphs beginning with a bolded description below) we first describe some key components. Within a group $g$ and monitoring period $m$, $F(t) = P(T \le t)$ is the cumulative distribution function of $T$ for all events beginning in that monitoring period. The overall hazard $\lambda (t) = P(T = t \mid T \ge t)$ can be defined in terms of $F(t)$ as $\lambda (t) = (F(t) - F(t-1))/(1-F(t-1))$. In addition, $\overline{F}(t) = 1 - F(t) = P(T > t) = \prod_{t_i \le t} (1 - \lambda(t_i))$, which is equivalent to the overall survival function in standard TTE analyses [@Geskus2020-tb].

The event-specific hazard is analogous to a cause-specific hazard in TTE analyses with competing risks. For event $s$ within group $g$ and monitoring period $m$, the event-specific hazard at $t_i$ is $\lambda_s (t_i) = P(T = t_i, S = s \mid T \ge t_i)$. Then, the corresponding event-specific cumulative incidence is $F_s(t) = P(T \le t, S = s) = \sum_{t_i \le t} \overline{F}(t_i)\lambda_s(t_i) = \sum_{t_i \le t} \theta (t_i)$ [@Geskus2020-tb]. Thus, the mean time without event $s$ is $\mu_s(\tau) = \sum_{t_i < \tau} (t_{i+1} - t_i)F_s(t_i)$ [@Conner2021-ac]. If we are comparing across sequential monitoring periods or groups, we write $\mu_{s,m}(\tau)$ to specify the monitoring period $m$ and $\mu_{s,g}(\tau)$ to specify group $g$.

Right censoring is assumed to be non-informative except for when an individual is censored due to a competing event. When an individual is recorded as having an event $s$ that has any competing events (e.g., if $s > 1$), they leave the risk set to be coded for any other competing event. Both $g=1$ and $g=0$ groups are expected have events recorded at all equivalent reporting times within the monitoring period. We also impose that the overall sample is fixed across all monitoring periods.

**Underreporting in comparison group.** The $s^* \ge 1$ reference events occur in $g=0$ only. So, in the comparison group $g=0$ only and two sequential monitoring periods $m-1$ and $m$, our estimand for the underreporting proportion $\epsilon$ is one minus the average persistence of all reference events, or $\epsilon = 1 - \frac{1}{h} \sum q_{s^*,m}$. Multiple pairs of sequential monitoring periods are distinguished by adding a subscript, $\epsilon_m$, where $m$ denotes the second monitoring period in a pair. More details for this estimand can be found in the appendix.

**Difference in mean time without event across groups.** We are first interested in estimating the difference in incident reporting for event $s$ across the two groups within one monitoring period. So, our estimand is $\psi = \mu_{s,g=1}(\tau) - \mu_{s,g=0}(\tau)$. A schematic illustration of this estimand as well as its underlying components is available in @fig-schematic. In a monitoring period where $\epsilon$ is known, the estimand is modified to account for underreporting by shifting the event-specific cumulative incidence curve in the comparison group $g=0$ by $\epsilon$, or $\mu^*_{s,g=0}(\tau) = \sum_{t_i < \tau} (t_{i+1} - t_i)(F_s(t_i) + \epsilon)$. This is written as $\psi^* = \mu_{s,g=1}(\tau) - \mu^*_{s,g=0}(\tau)$. Across the two groups in two sequential monitoring periods, the reported difference in mean time without event that does not account for underreporting is $\psi_{M} = \psi_m - \psi_{m-1}$. $\psi_m$ and $\psi_{m-1}$ are the same as $\psi$ but with an additional subscript to specify the monitoring period. This estimand can also be adjusted to account for underreporting when $\epsilon_m$ and $\epsilon_{m-1}$ are known, becoming $\psi_M^* = \psi^*_m - \psi^*_{m-1}$.

**Possible severity-based upcoding.** Possible severity-based upcoding can also be estimated within a monitoring period by comparing the difference in incident reporting of the most severe event versus the least severe event across groups. Here, $s \ge 2$, where the least severe subtype corresponds to $s = 1$ and the most severe subtype to $s = k$. In one monitoring period, possible severity-based upcoding across groups is $\omega = \omega_{g=1} - \omega_{g=0}$, where each $\omega_{g} = \mu_{s=k,g}(\tau) - \mu_{s=1,g}(\tau)$. If such reporting is higher in $g=1$ compared with $g=0$ (e.g., $\omega > 0$), then severity-based upcoding may be occurring.

### Estimators

In order to introduce the estimator of $\mu_s(\tau)$, we first describe the estimator for the event-specific hazard at $t_i$: $\hat{\lambda}_s(t_i) = d_{s,i}/r_i$, where $d_{s,i}$ is the count of event $s$ reported at $t_i$ and $r_i$ is the number of individuals at risk at $t_i$, meaning the number of individuals who have not yet been recorded as having $s$ or any competing event by $t_i$. $d_i = \sum d_{s,i}$ is the count of all competing events reported at $t_i$. We also have the event-specific cumulative incidence estimator: $\hat{F}_s(t) = \sum_{t_i \le t} \hat{\theta}(t_i)$, with $\hat{\theta}(t_i) = \widehat{\overline{F}}(t_i) \times \hat{\lambda}_s(t_i)$, where $\widehat{\overline{F}}(t) = \prod_{t_i \le t}(1 - \hat{\lambda}(t_i)) = \prod_{t_i \le t}(1 - (d_i/r_i))$ is the Kaplan-Meier estimator for $\overline{F}(t) = \prod_{t_i \le t}(1 - \lambda(t_i))$ [@Kaplan1958-ye; @Geskus2020-tb]. We can now define the estimator of $\mu_s(\tau)$ based on prior literature [@Conner2021-ac], as this is a component of the novel estimators we develop next: $\hat{\mu}_s(\tau) = \sum_{t_i < \tau} (t_{i+1} - t_i)\hat{F}_s(t_i)$. Variances and covariances for estimators in this section are in the appendix.

**Underreporting in comparison group.** For each reported reference event $s^*$ in $g=0$ we first compute persistence, or the proportion of individuals reported as having $s^*$ in monitoring period $m$ who where also reported as having $s^*$ in monitoring period $m-1$. This is then averaged across all reference events to obtain $\hat{\epsilon} = 1 - \frac{1}{h} \sum \hat{q}_{s^*,m}$.

**Difference in mean time without event across groups.** We propose that the difference in mean time without an event, $\psi$, is estimated across groups as $\widehat{\psi} = \hat{\mu}_{s,g=1}(\tau) - \hat{\mu}_{s,g=0}(\tau)$. To adjust for underreporting, $\hat{\mu}_{s,g=0}(\tau) = \sum_{t_i < \tau} (t_{i+1} - t_i) \hat{F}_{s}(t_i)$ is modified to $\hat{\mu}_{s,g=0}(\tau) = \sum_{t_i < \tau} (t_{i+1} - t_i) (\hat{F}_{s}(t_i) + \epsilon)$ in the estimator for $\widehat{\psi}$; this is denoted $\hat{\psi}^*$. Across sequential monitoring periods, $\psi_M$ is estimated as $\hat{\psi}_M = \hat{\psi}_m - \hat{\psi}_{m-1}$. When an underreporting estimate is known for both monitoring periods, this estimator becomes $\hat{\psi}_M^* = \hat{\psi}^*_m - \hat{\psi}^*_{m-1}$.

**Possible severity-based upcoding.** Our estimator $\omega$, is given by: $\widehat{\omega} = \widehat{\omega}_{g=1} - \widehat{\omega}_{g=0}$, where each $\widehat{\omega}_{g} = \hat{\mu}_{s=k}(\tau) - \hat{\mu}_{s=1}(\tau)$ within one monitoring period.

## Comparator estimator {#sec-comparator-estimator}

We compared our estimators to a coding intensity estimator similar to the Demographic Estimate of Coding Intensity (DECI), which is widely used by Medicare policymakers [@kronick2021a; @Medicare_Payment_Advisory_Commission2024-cg]. DECI assumes complete data (e.g., no censoring) and has the following formula:

$$
\begin{aligned}
\\ \text{DECI} = \frac{\frac{\text{National average MA CMS-HCC risk score}}{\text{National average TM CMS-HCC risk score}}}{\frac{\text{National average MA demographic-only CMS-HCC risk score}}{\text{National average TM demographic-only CMS-HCC risk score}}}.
\end{aligned}
$$

Here, the numerator is a risk score is estimated with both HCCs and demographic variables, while the denominator is estimated uses demographic variables only. Importantly, this also means that the estimand targeted by DECI is different from that of our proposed estimators. As we did not have CMS-HCC risk score coefficients or demographic variables available in our simulated data, our comparator estimator was more precisely DECI-like and defined as: $$
\begin{aligned}
\\ \text{DECI}^\dagger = \frac{\text{Average count of MA CMS-HCC HCCs}}{\text{Average count of TM CMS-HCC HCCs}}.
\end{aligned}
$$$\text{DECI}^\dagger$ is estimated in the same simulated data described earlier in this section, but relies on counts of all HCCs at the end of each monitoring period rather than time to incident coding of individual HCCs. Although DECI has a different target estimand than our estimators and ignores censoring, comparing our simulation results to $\text{DECI}^\dagger$ is useful as it illustrates how our estimators can be a complement to existing practice.

## `upcoding` R package

We developed the open source `upcoding` R package (https://github.com/StanfordHPDS/upcoding) to help address several issues in upcoding methods development by simulating longitudinal coding data for a Medicare-eligible population. Features include:

1.  **Simulating a sample of individuals with realistic baseline HCCs**. To simulate realistic co-occurring HCCs not influenced by coding incentives, sets of self-reported health conditions from participants aged 65 years and older (i.e., Medicare eligible) were extracted from the National Institutes of Health's All of Us study [@theall2019]. Baseline data were then simulated by sampling with replacement from these sets of co-occurring HCCs, where the respondent count weights sampling. The appendix includes survey summary statistics. This project has an Institutional Review Board exemption from All of Us because Stanford University has an institutional Data Use and Registration Agreement with the program, the data are anonymized, and we did not conduct human subjects research with the data. Our study also does not share any individual level All of Us data.

2.  **Upcoding baseline data to a specified level over multiple time points.** Users have the option to upcode any HCC using either any-available or severity-based upcoding. This results in labeled upcoding data, which is a useful resource for many types of coding measurement and estimation.

3.  **Undercoding baseline data to a specified level**. Users have the option to specify an undercoding proportion, and that proportion of all existing diagnoses are removed from the overall dataset. This can help simulate data that is similar to TM as a comparison group for analyses along with non-undercoded baseline data.

We describe this functionality in further detail in the appendix.

## Simulation study {#sec-simulation-study}

Our simulation study demonstrates how the estimators we propose can be used to monitor Medicare coding behaviors. To do this, different upcoding and underreporting scenarios for the estimator of $\psi$ were compared to estimates of $\text{DECI}^\dagger$. Degrees of upcoding and undercoding were constructed to align with current estimates of these issues in MA and TM from the literature. In addition, the temporal structure was implemented to be analogous to quarterly reporting for the length of time (around two years) that a given risk adjustment formula version is typically in place. We did not use individual-level Medicare data given that labeled upcoding is not available. Each individual scenario was replicated 1000 times.

In each replicate, two sets of 1,000,000 observations of baseline data were independently simulated using our `upcoding` package. For each dataset, the columns are the V28 HCCs (listed in appendix). Both any-available and severity-based upcoding were implemented in the first baseline data set (the MA data). For the former type of upcoding, an HCC without any competing HCCs (HCC238, Specified Heart Arrhythmias) was upcoded. For the latter we upcoded HCC125 (Dementia, Severe). HCC125's less severe HCCs are HCC126 (Dementia, Moderate) and HCC127 (Dementia, Mild or Unspecified). The scenarios implemented were as follows:

**Scenario 1. Any-available upcoding of an HCC that lacks competing events (HCC238) with varying underreporting in the comparison group.** Baseline MA data were separately upcoded to varying degrees (20%, 25%, 30%) sequentially within each monitoring period. The comparison group (i.e., TM data) was simulated by first undercoding the baseline TM data to varying levels (0%, 5%, 10%, 15%) and then upcoding HCC238 analogously but to a lower amount (5%) per monitoring period.

**Scenario 2. Lower-severity upcoding of an HCC with competing events (HCC125) with varying underreporting in the comparison group.** Baseline MA data were separately upcoded to varying degrees (20%, 25%, 30%) sequentially within each monitoring period. The comparison group was simulated by first undercoding the baseline TM data to varying levels (0%, 5%, 10%, 15%) and then upcoding HCC125 analogously but to a lower amount (5%) per monitoring period.

# Results

## Proposed estimators

Cumulative incidence of coding for scenario 1 given 20% any-available upcoding in MA and 5% any-available upcoding in TM after all four degrees of undercoding is shown in @fig-cif. As expected, within each monitoring period the cumulative incidence of the upcoded group was higher than the comparison group, which was only upcoded 5%. We also saw that the impact of undercoding on cumulative incidence estimates was limited. Given that undercoding occurs across the entire set of 115 HCCs, it was less likely to notably influence estimates for any single HCC. Lastly, we observed that the gaps between upcoded and comparison groups become smaller in sequential monitoring periods, which is a consequence of the fixed sample we imposed across all monitoring periods. As monitoring periods increased, the number of individuals available to upcode decreased. Results plots for additional degrees of upcoding (25%, 30%) and Scenario 2 upcoding (severity-based upcoding for HCC125) are in the appendix.

Estimates corresponding to the $\psi$ estimator for upcoding of HCC238 are presented in @fig-psi, which examines the difference in time without reported incident HCC238 coding between MA and TM within each monitoring period. Examining the first monitoring period (M1), estimates clearly increase with the degree of upcoding. Similarly, for monitoring period 2 (M2) alone, estimates also increase with the degree of upcoding.

In addition, undercoding has a limited effect on estimates. However, researchers also have the option to adjust for underreporting using the estimator proposed for underreporting. As the sample is fixed across monitoring periods, estimates across monitoring periods within a degree of upcoding and undercoding decrease, analogously to @fig-cif. The gap between M1 and M2 increases with degree of upcoding as well, because more aggressive incident upcoding in M1 limits the availability of individuals for incident upcoding in M2.

This suggests that within a monitoring period, researchers could compare estimates of different HCCs to obtain a ranked list of HCCs to study further, where HCCs with the highest estimates have the most incident coding. In addition, in this scenario, being in TM appeared to have a "protective effect" against being coded with HCC238, although supplemental analyses would be needed to account for possible confounding and other issues. Additional results plots for severity-based upcoding of HCC125 are available in the appendix.

## Comparator estimator

@fig-deci shows the average $\text{DECI}^\dagger$ estimate across simulation replicates by monitoring period as well as upcoding and undercoding degree. As degree of upcoding increases, these estimates increase negligibly both for individual monitoring periods and across sequential monitoring periods. This is intuitive–only two of the 115 HCCs in the current MA risk adjustment algorithm are being upcoded–but suggests a limitation of DECI in identifying upcoding occurring in a minority of HCCs. Regardless of upcoding degree, the $\text{DECI}^\dagger$ estimate increasing in line with the degree of TM undercoding indicates that it may be more sensitive to undercoding in TM. Especially since we know undercoding is prevalent in TM [@Ellis2018-mr; @Ghoshal-Datta2024-io], this suggests that DECI may be underestimating overall spending gap between MA and TM.

# Discussion

We proposed a set of estimators that extend RMTL methodology for evaluating time to incident coding by private insurers in Medicare. Given the timeline of CMS-HCC updates, our approach realistically presupposes that reported coding is examined over multiple monitoring periods, each of which has several time points where new events are reported. Novel estimators were introduced to evaluate differences in time-to-reporting both within monitoring periods and across monitoring periods, including an estimator for severity-based upcoding. Our approach also included an adjustment for possible underreporting, which is a known major issue in TM data [@Ellis2018-mr; @Ghoshal-Datta2024-io]. Finally, we developed an open source R package that enables users to simulate co-occurring HCCs free of coding incentives and similar to those reported by individuals residing in the United States eligible for Medicare. Users can also undercode or upcode this data over time.

Our simulated data were upcoded to degrees aligned to those reported in literature [@Medpac2025-uh], and we found in our simulation results that our estimators were able to recover differences in upcoding both within and across monitoring periods while showing limited sensitivity to undercoding. DECI-like estimates of the same data were a useful complement, but were limited in that these comparator estimates were very sensitive to undercoding and did not vary when upcoding occurred in a minority of HCCs. Therefore, our estimators show considerable promise as tools to help evaluate reported coding patterns over time. These estimators can be used as a first step to identify potentially upcoded HCCs while making more realistic assumptions than DECI. Follow up analyses could include examining coding patterns within specific insurers, providers, or beneficiaries.

This work has a number of limitations and areas for future development. First, several assumptions could be further relaxed. This includes our assumptions that the population is fixed across both comparison groups and monitoring periods and that estimates in sequential monitoring periods across groups are approximately independent. However, doing so could also make establishing a diagnosis as incident and comparing estimates across monitoring periods more challenging. Upcoding estimators could be expanded to additional types of upcoding and to correct for underreporting. Covariates could also be incorporated into estimation to better address issues like confounding. There is also more heterogeneity and missingness in real-world claims data than was included in our simulations. Self-reported diagnoses---as we use in our simulated baseline data---also have recall bias and other issues that we do not address here.

Since the MA program's inception, high intensity of private insurer coding, including possible upcoding, is estimated to have cost the federal government and taxpayers \$224 billion dollars without clear benefit to beneficiaries [@Medpac2025-uh]. Thus, estimating differences in coding between MA and TM or more and less severe competing HCCs has the potential to help policymakers locate issues with specific HCCs earlier and at scale. This could suggest areas for improvement in the risk adjustment formula and potentially save significant funds in the Medicare program. Our work has provided both novel estimators and novel simulated data tailored to addressing these important policy considerations.

{{< pagebreak >}}

# Figures

![**Schematic figure of notation for evaluating coding intensity of the Hierarchical Condition Category (HCC) denoted by** $s$: This HCC is assumed to have no competing events. The visuals and notation in this figure illustrate components of the difference in mean time without event across groups estimator, or $\psi$, within two separate monitoring periods. $\psi$ corresponds to the difference of restricted mean time lost up until a pre-specified end time $\tau$ between a group $g$ of interest ($g=1$, e.g., Medicare Advantage) and a reference group ($g=0$, e.g., Traditional Medicare). Other reporting time points within each monitoring period are denoted $t_1$, $t_2$, and $t_3$ and also have an optional subscript $m$ to denote which monitoring period it corresponds to of the two shown.](images/enache_figure1.png){#fig-schematic width="60%"}

{{< pagebreak >}}

![**Cumulative incidence functions for the Specified Heart Arrhythmias Hierarchical Condition Category (HCC) in simulated Medicare Advantage (MA) and Traditional Medicare (TM) groups: 20% any-available MA upcoding.** 20% any-available MA upcoding. Specified heart arrhythmias corresponds to HCC238, which does not have any competing events. For this HCC, 20% of any-available individuals in the MA group are upcoded and 5% of any-available individuals in the TM comparison group are upcoded. The first monitoring period is labeled M1, and the second monitoring period is labeled M2. Given the large sample size, confidence intervals are very narrow and are therefore omitted as they cannot be distinguished visually.](images/enache_figure2.png){#fig-cif width="90%"}

{{< pagebreak >}}

![**Within-monitoring period period** $\boldsymbol{\psi}$ **estimates** **for the Specified Heart Arrhythmias Hierarchical Condition Category (HCC) in simulated Medicare Advantage (MA) and Traditional Medicare (TM) groups.** $\widehat{\psi}$ corresponds to the proposed estimator for $\psi$, or the difference in mean time without event (i.e., incident coding of the HCC) across groups. Specified heart arrhythmias corresponds to HCC238, which does not have any competing events. For this HCC, any-available individuals in the MA group are upcoded to varying degrees and any-available individuals in the TM comparison group are upcoded 5%. The first monitoring period is labeled M1, and the second monitoring period is labeled M2. Given the large sample size, confidence intervals are very narrow and are therefore omitted as they cannot be distinguished visually.](images/enache_figure3.png){#fig-psi width="90%"}

{{< pagebreak >}}

![$\textbf{DECI}^\dagger$ **estimate across all Medicare Advantage (MA) Version 28 Hierarchical Condition Categories (HCCs) at varying degrees of upcoding and underreporting in simulated MA and Traditional Medicare (TM) groups.** The Demographic Estimate of Coding Intensity (DECI) is an estimator widely used by policymakers to evaluate coding intensity within a year by comparing ratios of average risk scores in MA versus TM; $\text{DECI}^\dagger$ is our slight modification of this estimand due to data availability, and $\widehat{\text{DECI}}^\dagger$ is its estimate. Three separate degrees of MA group upcoding occur sequentially over each monitoring period in HCC238 (any-available) and HCC125 (lower severity) only. The TM group is upcoded 5% sequentially for the same HCCs over equivalent periods. The first monitoring period is labeled M1, and the second monitoring period is labeled M2. Given the large sample size, confidence intervals are very narrow and are therefore omitted as they cannot be distinguished visually.](images/enache_figure4.png){#fig-deci width="90%"}

{{< pagebreak >}}

# Acknowledgments

This research was funded by National Institutes of Health Director's Pioneer Award DP1LM014278 and a Stanford Interdisciplinary Graduate Fellowship. We thank Malcolm Barrett, Gabriela Basel, Lizzie Kumar, and Neha Srivathsa for their valuable insights and contributions to code performance and review. We gratefully acknowledge All of Us participants for their contributions, without whom this research would not have been possible. We also thank the National Institutes of Health’s All of Us Research Program (https://allofus.nih.gov/) for making available the participant survey data included in this study. We thank Stanford University and Stanford Research Computing for providing additional computational resources, including support for computing performed on the Sherlock cluster.

# Conflict of interest statement

None to report.

{{< pagebreak >}}

# References